#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dask
Version  : 1.1.2
Release  : 52
URL      : https://files.pythonhosted.org/packages/d5/28/cb70b1c9f07e783b42145c787049b3a731eb0dece5e179aeef5e646b2706/dask-1.1.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/d5/28/cb70b1c9f07e783b42145c787049b3a731eb0dece5e179aeef5e646b2706/dask-1.1.2.tar.gz
Summary  : Parallel PyData with Task Scheduling
Group    : Development/Tools
License  : BSD-3-Clause
Requires: dask-license = %{version}-%{release}
Requires: dask-python = %{version}-%{release}
Requires: dask-python3 = %{version}-%{release}
Requires: cloudpickle
Requires: distributed
Requires: numpy
Requires: pandas
Requires: partd
Requires: toolz
BuildRequires : buildreq-distutils3
BuildRequires : pytest-runner

%description
Dask
====
|Build Status| |Coverage| |Doc Status| |Gitter| |Version Status|
Dask is a flexible parallel computing library for analytics.  See
documentation_ for more information.

%package license
Summary: license components for the dask package.
Group: Default

%description license
license components for the dask package.


%package python
Summary: python components for the dask package.
Group: Default
Requires: dask-python3 = %{version}-%{release}

%description python
python components for the dask package.


%package python3
Summary: python3 components for the dask package.
Group: Default
Requires: python3-core

%description python3
python3 components for the dask package.


%prep
%setup -q -n dask-1.1.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551126817
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/dask
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/dask/LICENSE.txt
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/dask/LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
